### ISSUE TITLE
Moving target - Clear always

### ISSUE THREAD

**Issue by OwlBawl** [Rihan9/LD2412#1]
While HLK app shows prensence and Out pit triggered

**Comment by Rihan9** [comment]
Hi,
For the next time, can you please explain better what is the problem? 
I understand that while on the app you have detected the motion presence and on the device you have the OUT pin triggered. 
Instead In the espHome device the motion presence entity is not triggered. What about the general one?

**Comment by OwlBawl** [comment]
exactly
all that belongs to Move is steady 0

using your basic config from examples. Presence and presence distance is ok, so uart is working.

<img width="323" alt="Screenshot 2024-09-20 at 20 25 32" src="https://github.com/user-attachments/assets/29236369-f830-4a57-bbeb-0cbf27f366d4">

**Comment by Rihan9** [comment]
Hi @OwlBawl,
do your app report an active moving target presence for more than a second? I got queasiness walking around my room with my cellphone on hand and I was unable to get it.

What is your LD2412 firmware version?

**Comment by OwlBawl** [comment]
set mov.sensitivity threshold to min, get 1+ sec movement state in HLK app
Reised uart bus speed to 256000 also
But no luck. They all still always.
Updated HLK to 1.24.24 last version

**Comment by Rihan9** [comment]
Thanks @OwlBawl!
Thanks to your report I found a pretty nasty piece of code that caused the component to skip almost all the periodic message sended by the sensor. This problem probably caused also latency issues.

Can you please recheck? If this problem is not fixed for you, feel free to reopen this issue.
