### ISSUE TITLE
engineering_mode

### ISSUE THREAD

**Issue by bato2000** [Rihan9/LD2412#13]
Hi. I'm trying to add Home Assistant to the LD2412, but for some reason I can't activate the engineer mode. I don't know if I've written it wrong. Because the rest of the things do work.
thank you

<img width="536" alt="Captura de pantalla 2024-11-05 a las 10 28 52" src="https://github.com/user-attachments/assets/89aeba34-cb57-4291-9354-0857f7153ab5">

<img width="756" alt="Captura de pantalla 2024-11-05 a las 10 23 11" src="https://github.com/user-attachments/assets/886e9990-b073-42ba-b464-a0966b17177a">

**Comment by Rihan9** [comment]
Hi,
please refer to the example on the main page of this repo. Engineering mode is not a switch but part of the "mode select

```
select:
  - platform: LD2412
    mode:
      name: "Mode"
```

**Comment by bato2000** [comment]
thanks

**Comment by Rihan9** [comment]
I'm closing this issue
