### ISSUE TITLE
wiring diagram?

### ISSUE THREAD

**Issue by markmghali** [Rihan9/LD2412#15]
I have wired an ld2410 with an esp32. Trying to use an esp32 s3 now. Also confused by the extra pins on the ld2412. Do I use 3v or 5v on the ld2412? Thank you

**Comment by benbox69** [comment]
Hi,
I personally use 5V as when I use 3.3V with other sensors I have a strange behavior…

**Comment by markmghali** [comment]
Thank you @benbox69! So to clarify, I only need to wire the 5v, 1 of the GND and the TX, RX pins and the out pin is optional

**Comment by benbox69** [comment]
Yes, it’s how I connected it 👍🏻

**Comment by Rihan9** [comment]
Hi, I don't think is a good idea to write an issue about the wiring diagram here. If you have a generic question on need help, there is a conversation abount it in the home assistant community:

https://community.home-assistant.io/t/diy-human-sensor-l12-base-on-hlk-ld2412/758421/61

In the end, were you able to connect the sensor?

**Comment by markmghali** [comment]
Yes i did thank you! Sorry for any confusion
