### ISSUE TITLE
Presence detection doesn't align with gates thresholds

### ISSUE THREAD

**Issue by yanivf38** [Rihan9/LD2412#9]
Hi @Rihan9 ,

The presence trigger doesn't seem to align with the thresholds. By default, all the still gates thresholds are set to 15%. I am looking at the data and as you can see it passed the threshold multiple times, but the presence doesn't get triggered. Is it due to the throttle?

![thereshold detection](https://github.com/user-attachments/assets/c53c1c21-467b-4491-a44a-903d288e6384)

**Comment by Rihan9** [comment]
Hi,
you have done a pretty nice job with this. But I'm sorry to reply that is not something that I can help you with. The presence itself is managed by the sensor's firmware, the only think that my component do is to read the uart message and report it. The gate energy and the presence flag are part of the same message so is not even a throttle problem.
I can think of discard the presence flag from the sensor's message and use the threshold and energy value to calculate the presence value on the esp, but this could be quite a challenge, mostly in:
- cpu usage
- debouncing
- other thnks that I don't see right now

Let me think about it more

**Comment by yanivf38** [comment]
Thank you @Rihan9 ,

I'm not sure of the consequences of having the sensor constantly in eng mode in order to process the gates manually. If it's not a bug in the firmware the only thing I can think of is that the threshold values that are read from gates are wrong

**Comment by Rihan9** [comment]
> If it's not a bug in the firmware the only thing I can think of is that the threshold values that are read from gates are wrong

In teory, we can check this using the app but the problem is the different refresh rate between them. I think I need to record the screen on my phone and use the presence detection as sync trigger. It's gonna be a pain! Just another day of work and it's the weekend. I'll try to set up a testing environment and I'll try to do it. Wish me a good luck ahahah

**Comment by yanivf38** [comment]
Good luck :-)
I'll try to put another sensor to see how it behaves. I noticed that HLK have a new firmware. I tried upgrading my sensor but it failed switching to the new firmware once it downloaded it to the SoC.

**Comment by Rihan9** [comment]
Hi @yanivf38,
I performed the upgrade to the 1.24.24092417 firmware version with success. The integration keep working just fine for me. Make sure to follow the instruction from the app. Other than this, I don't know any other advice to give you.

**Comment by Rihan9** [comment]
Hi @yanivf38,
I runned some tests and it doesn't seems to be an error on this component but a bug on the LD2412 firmware. I don't have a way to fix this, so let's hope that the productor we'll see this bug and fix it. The latest firmware doesn't seem to do it unfortunately.

**Comment by yanivf38** [comment]
Thank you @Rihan9, make sense. I also tried the other firmware with no luck. Like you I hope their devs read these threads.

Some other comments (not related to your code but good to point out -
1) firmware upgrade : trying to upgrade the firmware using Samsung Note 20 and S24 always fails. However, using an old android device upgrade the chip with no issues.
2) Detection seem weird - the ld2412 has taken a while before it triggers detection and however, it works more accurately keeping the detection until it needs to turn it off.
